# Generated by Django 6.0.4 on 2026-04-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanoramicXRay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xrays/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('has_caries', models.BooleanField(default=False)),
                ('has_impaction', models.BooleanField(default=False)),
                ('has_bone_loss', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
