# Generated by Django 6.0.4 on 2026-05-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panoramicxray',
            name='has_crown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panoramicxray',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='xrays/processed/'),
        ),
        migrations.AlterField(
            model_name='panoramicxray',
            name='image',
            field=models.ImageField(upload_to='xrays/originals/'),
        ),
    ]
